### ISSUE TITLE
The yellow text link doesn’t look very legible 

### ISSUE THREAD

**Issue by lil5** [matthewhowell/reasonable-colors#5]
![71A3980B-FBF3-4646-B69D-B6F1E630BB6B](https://user-images.githubusercontent.com/17646836/164968547-144271b7-0075-43f7-b4ed-d54956c73112.jpeg)

on my phone at least the text is difficult to read

**Comment by matthewhowell** [comment]
I think you're correct, looks like I used the wrong shade here. Thanks!

**Comment by matthewhowell** [comment]
Fixed by changing to yellow shade 3, which has better contrast for this item.
